# Generated by Django 4.0.4 on 2022-05-31 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='body',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tweets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
