# Generated by Django 4.0.4 on 2022-06-02 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_tweet_image_alter_tweet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
