# Generated by Django 4.0.4 on 2022-06-09 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_tweet_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='tweets_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
